---
- name: "start container"
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    ports:
      - "3000:3000"
    env:
      environment: "{{ env }}"
      port: "{{ port }}"
      owner: "{{ owner }}"
      purpose: "{{ purpose }}"

